const campusProfiles = [
  { 
    id: 'upenn', 
    name: 'University of Pennsylvania', 
    slug: 'upenn',
    location: 'Philadelphia, PA', 
    vibe: 'Competitive & Pre-professional',
    student_count: '10,000',
    acceptance_rate: '6%',
    popular_majors: ['Finance', 'Nursing', 'Philosophy'],
    housing: '100% Guaranteed',
    gpa_range: '3.9+',
    test_scores: '1510-1570 SAT',
    grad_rate: '96%',
    retention_rate: '98%',
    major_count: '90+',
    double_major_ease: 'Requires Approval',
    class_size: '20 (Seminar) / 200 (Intro)',
    grading_culture: 'Varies by Dept (Wharton Curved)',
    housing_guarantee: '4 Years',
    residential_culture: 'Socially tiered, Greek dominant',
    party_scene: 'Dominant social outlet (Frats/Bars)',
    dating_scene: 'High-pressure/Coupled',
    mental_health: 'Fast-paced, high academic pressure',
    food_quality: 'Decent (Multiple options)',
    setting: 'Urban (West Philly)',
    transportation: 'Walkable / SEPTA accessible',
    climate: 'Four Seasons',
    sticker_price: '$85,000',
    avg_aid: '$60,000',
    need_blind: true,
    personality: 'Hyper-ambitious, outcome-oriented, socially tiered.',
    stress_level: '9/10',
    fomo_factor: 'Severe',
    deep_dive: "The network at UPenn revolves around the 'Quaker' ethos—efficiency and outcome-oriented connections. Students are often balancing double-majors and early-stage ventures.",
    student_quote: "Nobody tells you about the 'Wharton Fog'—it's not just a major, it's a social gravity that affects everyone.",
    misconception: "That everyone is at Wharton. The College and Engineering have their own intense subcultures."
  },
  { 
    id: 'berkeley', 
    name: 'UC Berkeley', 
    slug: 'berkeley',
    location: 'Berkeley, CA', 
    vibe: 'Huge & Decentralized',
    student_count: '32,000',
    acceptance_rate: '11%',
    popular_majors: ['CS', 'Econ', 'Cell Biology'],
    housing: '60% (Limited)',
    gpa_range: '3.89-4.00',
    test_scores: 'N/A (Test Blind)',
    grad_rate: '92%',
    retention_rate: '97%',
    major_count: '150+',
    double_major_ease: 'Easy if in same college',
    class_size: '30 (Seminar) / 800 (CS61A)',
    grading_culture: 'Rigorous (Deflation in STEM)',
    housing_guarantee: '1 Year (Usually)',
    residential_culture: 'Scattered, vibrant, politically active',
    party_scene: 'Co-ops & Frats; very decentralised',
    dating_scene: 'Casual/Fluid',
    mental_health: 'Navigating bureaucracy is a stressor',
    food_quality: 'Gourmet Ghetto nearby is amazing',
    setting: 'Urban / Hills',
    transportation: 'BART / Extremely walkable',
    climate: 'Mild / Constant spring',
    sticker_price: '$45,000 (In-state)',
    avg_aid: '$25,000',
    need_blind: true,
    personality: 'Intellectually fierce, radical, DIY-ethos.',
    stress_level: '8.5/10',
    fomo_factor: 'Moderate',
    deep_dive: "Berkeley doesn't hold your hand. You have to fight for resources, but finding your 'tribe' in a 30,000-person sea is part of the growth process.",
    student_quote: "If you want a safe bubble, don't come here. If you want to see the world as it's becoming, apply.",
    misconception: "That it's all protests. Most people are just in the library trying to survive EECS."
  },
  { 
    id: 'stanford', 
    name: 'Stanford University', 
    slug: 'stanford',
    location: 'Stanford, CA', 
    vibe: 'Founder-led & Sunny',
    student_count: '7,700',
    acceptance_rate: '4%',
    popular_majors: ['CS', 'Engineering', 'Human Bio'],
    housing: '99% Guaranteed',
    gpa_range: '3.95+',
    test_scores: '1500-1570 SAT',
    grad_rate: '95%',
    retention_rate: '98%',
    major_count: '65+',
    double_major_ease: 'Very flexible',
    class_size: '15 (Small classes) / 300 (Intro)',
    grading_culture: 'Supportive (Grade inflation)',
    housing_guarantee: '4 Years',
    residential_culture: 'Theme-house centric',
    party_scene: 'Low-key/Dorm-based; restricted Greek life',
    dating_scene: 'Socially awkward/Pre-professional',
    mental_health: 'Duck Syndrome is the primary theme',
    food_quality: 'Varied (High residential quality)',
    setting: 'Suburban (The Farm)',
    transportation: 'Bikes required / Caltrain nearby',
    climate: 'Sunny / California Coastal',
    sticker_price: '$82,000',
    avg_aid: '$65,000',
    need_blind: true,
    personality: 'Founding-culture, elite access, high-pressure chill.',
    stress_level: '7.5/10 (Duck Syndrome)',
    fomo_factor: 'High',
    deep_dive: "Stanford mentorship is the ultimate gateway to Sand Hill Road. The 'Stanford Social Graph' is uniquely optimized for early-stage funding.",
    student_quote: "It's called the 'Duck Syndrome'—everyone looks calm on the surface but they're paddling like hell underneath.",
    misconception: "That everyone is a tech bro. The arts and humanities scene is surprisingly robust."
  },
];

export default campusProfiles;
