const coreMentors = [
  {
    id: 'person_1',
    name: 'Marc Laurent',
    background: "Oxford '27, Economics; grew up between London and Paris",
    currentRole: 'Hotel Manager, Four Seasons Paris',
    expertise: ['luxury real estate', 'hospitality ops', 'paris market'],
    interests: ['service design', 'hotel real estate', 'Paris private markets'],
    goals: ['help students understand luxury hospitality careers', 'meet thoughtful operators'],
    relationshipPreferences: ['specific asks', '15 minute calls', 'Paris or UK context'],
    location: 'Paris, France',
    industries: ['hospitality', 'luxury real estate'],
    willingToMentor: true,
    contact: 'marc.laurent@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/marc-laurent-mock',
  },
  {
    id: 'person_2',
    name: 'Amara Okafor',
    background: "LSE '20, International Relations; former student society president",
    currentRole: 'Associate, McKinsey London',
    expertise: ['consulting recruiting', 'case interviews', 'uk universities'],
    interests: ['education access', 'case coaching', 'London student networks'],
    goals: ['support first-generation candidates', 'meet ambitious students exploring consulting'],
    relationshipPreferences: ['clear prep questions', 'UK university context', 'short follow-ups'],
    location: 'London, United Kingdom',
    industries: ['consulting', 'education'],
    willingToMentor: true,
    contact: 'amara.okafor@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/amara-okafor-mock',
  },
  {
    id: 'person_3',
    name: 'Sofia Mendes',
    background: "Sciences Po '22; built student climate policy network",
    currentRole: 'Policy Analyst, OECD',
    expertise: ['public policy', 'climate strategy', 'international organizations'],
    interests: ['climate careers', 'policy research', 'international institutions'],
    goals: ['help students navigate policy paths', 'meet people building serious research projects'],
    relationshipPreferences: ['policy-specific questions', 'research interests', 'Paris context'],
    location: 'Paris, France',
    industries: ['policy', 'climate'],
    willingToMentor: true,
    contact: 'sofia.mendes@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/sofia-mendes-mock',
  },
  {
    id: 'person_4',
    name: 'Julien Moreau',
    background: "HEC Paris '19; family background in boutique hotels",
    currentRole: 'Founder, MaisonKey',
    expertise: ['hospitality startups', 'marketplaces', 'fundraising'],
    interests: ['boutique hotels', 'marketplace trust', 'early-stage sales'],
    goals: ['meet founders with practical market insight', 'help operators test hospitality ideas'],
    relationshipPreferences: ['startup context', 'clear experiments', 'founder mindset'],
    location: 'Paris, France',
    industries: ['startups', 'hospitality'],
    willingToMentor: true,
    contact: 'julien.moreau@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/julien-moreau-mock',
  },
  {
    id: 'person_5',
    name: 'Nina Shah',
    background: "Cambridge '24, Land Economy; interned at Savills",
    currentRole: 'Analyst, Knight Frank Private Office',
    expertise: ['luxury property', 'uk studies', 'real estate investing'],
    interests: ['private-office real estate', 'UK universities', 'asset research'],
    goals: ['help students understand property careers', 'meet people serious about real estate'],
    relationshipPreferences: ['researched questions', 'UK academic angle', 'real estate focus'],
    location: 'London, United Kingdom',
    industries: ['real estate', 'finance'],
    willingToMentor: true,
    contact: 'nina.shah@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/nina-shah-mock',
  },
  {
    id: 'person_6',
    name: 'Theo Van Dijk',
    background: "TU Delft '21; exchange semester at Imperial College",
    currentRole: 'Product Manager, Booking.com',
    expertise: ['travel tech', 'product management', 'market research'],
    interests: ['travel marketplaces', 'user research', 'product discovery'],
    goals: ['mentor product-curious students', 'meet builders interested in travel'],
    relationshipPreferences: ['product questions', 'market research examples', 'concise context'],
    location: 'Amsterdam, Netherlands',
    industries: ['technology', 'travel'],
    willingToMentor: true,
    contact: 'theo.vandijk@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/theo-van-dijk-mock',
  },
  {
    id: 'person_7',
    name: 'Camille Dubois',
    background: "ESSEC '18; started in luxury brand partnerships",
    currentRole: 'Partnerships Lead, LVMH Maison Network',
    expertise: ['luxury brands', 'partnerships', 'paris networking'],
    interests: ['brand partnerships', 'luxury communities', 'Paris events'],
    goals: ['help people understand luxury networks', 'meet high-context partnership thinkers'],
    relationshipPreferences: ['warm context', 'luxury interest', 'specific collaboration ideas'],
    location: 'Paris, France',
    industries: ['luxury', 'marketing'],
    willingToMentor: true,
    contact: 'camille.dubois@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/camille-dubois-mock',
  },
  {
    id: 'person_8',
    name: 'David Chen',
    background: "Stanford '16, Computer Science; mentors first-time founders",
    currentRole: 'Partner, Seedline Ventures',
    expertise: ['startup validation', 'ai products', 'early-stage fundraising'],
    interests: ['AI products', 'founder-market fit', 'student startups'],
    goals: ['meet sharp early builders', 'help founders avoid vague validation'],
    relationshipPreferences: ['clear problem statements', 'traction signals', 'direct asks'],
    location: 'San Francisco, United States',
    industries: ['venture capital', 'ai'],
    willingToMentor: true,
    contact: 'david.chen@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/david-chen-mock',
  },
  {
    id: 'person_9',
    name: 'Leila Haddad',
    background: "Bocconi '23, Finance; summer analyst in Dubai",
    currentRole: 'Analyst, J.P. Morgan Private Bank',
    expertise: ['private banking', 'wealth management', 'middle east markets'],
    interests: ['wealth management', 'Dubai markets', 'finance careers'],
    goals: ['help students decode private banking', 'meet people interested in global finance'],
    relationshipPreferences: ['finance focus', 'regional curiosity', 'prepared questions'],
    location: 'Dubai, United Arab Emirates',
    industries: ['finance', 'wealth management'],
    willingToMentor: true,
    contact: 'leila.haddad@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/leila-haddad-mock',
  },
  {
    id: 'person_10',
    name: 'Hugo Stein',
    background: "IE University '21; former student admissions ambassador",
    currentRole: 'Growth Manager, Too Good To Go',
    expertise: ['food initiatives', 'growth experiments', 'european startups'],
    interests: ['food systems', 'growth loops', 'student initiatives'],
    goals: ['support practical student projects', 'meet people testing sustainability ideas'],
    relationshipPreferences: ['experiment mindset', 'European context', 'clear next step'],
    location: 'Madrid, Spain',
    industries: ['food tech', 'sustainability'],
    willingToMentor: true,
    contact: 'hugo.stein@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/hugo-stein-mock',
  },
  {
    id: 'person_11',
    name: 'Priya Raman',
    background: "Wharton MBA '20; built a student mentorship nonprofit",
    currentRole: 'Chief of Staff, GlobalEd Foundation',
    expertise: ['mentorship programs', 'education nonprofits', 'operations'],
    interests: ['education systems', 'mentorship design', 'nonprofit operations'],
    goals: ['help people build useful networks', 'meet operators improving education'],
    relationshipPreferences: ['mission clarity', 'operations questions', 'student impact'],
    location: 'New York, United States',
    industries: ['education', 'nonprofit'],
    willingToMentor: true,
    contact: 'priya.raman@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/priya-raman-mock',
  },
  {
    id: 'person_12',
    name: 'Antoine Berger',
    background: "EHL '17; trained across rooms, F&B, and revenue management",
    currentRole: 'Director of Operations, Mandarin Oriental Geneva',
    expertise: ['hotel operations', 'service excellence', 'hospitality careers'],
    interests: ['service excellence', 'hotel operations', 'luxury guest experience'],
    goals: ['mentor hospitality students', 'meet people with operational curiosity'],
    relationshipPreferences: ['hospitality focus', 'practical questions', 'service mindset'],
    location: 'Geneva, Switzerland',
    industries: ['hospitality', 'luxury'],
    willingToMentor: true,
    contact: 'antoine.berger@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/antoine-berger-mock',
  },
  {
    id: 'person_13',
    name: 'Maya Collins',
    background: "Harvard '25, Social Studies; runs peer college advising sessions",
    currentRole: 'Research Assistant, Harvard Kennedy School',
    expertise: ['us universities', 'research projects', 'student leadership'],
    interests: ['college advising', 'social research', 'student leadership'],
    goals: ['support students navigating US universities', 'meet research-driven peers'],
    relationshipPreferences: ['student context', 'research interests', 'clear questions'],
    location: 'Cambridge, United States',
    industries: ['academia', 'public policy'],
    willingToMentor: true,
    contact: 'maya.collins@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/maya-collins-mock',
  },
  {
    id: 'person_14',
    name: 'Rafael Costa',
    background: "INSEAD MBA '18; launched expansion teams in Brazil and France",
    currentRole: 'International Expansion Lead, Airbnb',
    expertise: ['market entry', 'community operations', 'travel marketplaces'],
    interests: ['market expansion', 'community operations', 'travel ecosystems'],
    goals: ['help people understand new-market launches', 'meet global operators'],
    relationshipPreferences: ['market-specific questions', 'operator mindset', 'international context'],
    location: 'Sao Paulo, Brazil',
    industries: ['travel', 'marketplaces'],
    willingToMentor: true,
    contact: 'rafael.costa@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/rafael-costa-mock',
  },
  {
    id: 'person_15',
    name: 'Elena Rossi',
    background: "UCL '19, Urban Studies; former real estate analyst",
    currentRole: 'Development Manager, AccorInvest',
    expertise: ['hotel real estate', 'urban development', 'asset strategy'],
    interests: ['hotel assets', 'urban development', 'investment strategy'],
    goals: ['help students connect hospitality and real estate', 'meet people studying cities'],
    relationshipPreferences: ['real estate angle', 'urban studies context', 'specific asset questions'],
    location: 'Milan, Italy',
    industries: ['real estate', 'hospitality'],
    willingToMentor: true,
    contact: 'elena.rossi@example.com',
    linkedinUrl: 'https://www.linkedin.com/in/elena-rossi-mock',
  },
]

const additionalMentors = [
  ['person_16', 'Ines Fournier', "ESCP '20; started in Paris luxury retail operations", 'Operations Lead, Cheval Blanc Paris', ['luxury hospitality', 'guest experience', 'service operations'], ['guest journey design', 'luxury retail', 'Paris hospitality'], ['mentor students exploring high-touch service careers', 'meet people with practical operational curiosity'], ['Paris context', 'service-specific questions', 'short calls'], 'Paris, France', ['hospitality', 'luxury']],
  ['person_17', 'Omar Al Mansouri', "Cambridge Judge MBA '19; former real estate family office analyst", 'Investment Manager, Dubai Holding Real Estate', ['real estate investing', 'family offices', 'middle east property'], ['property underwriting', 'family capital', 'Dubai market'], ['help people understand real estate investment roles', 'meet serious finance-curious students'], ['prepared questions', 'finance focus', 'regional context'], 'Dubai, United Arab Emirates', ['real estate', 'finance']],
  ['person_18', 'Claire Whitman', "Oxford '18, PPE; moved from policy to venture", 'Principal, Northzone', ['venture capital', 'consumer startups', 'career pivots'], ['founder quality', 'market timing', 'student startups'], ['help early builders sharpen ideas', 'meet founders with unusual insight'], ['clear problem statements', 'traction signals', 'direct asks'], 'London, United Kingdom', ['venture capital', 'startups']],
  ['person_19', 'Mateo Alvarez', "IESE MBA '21; launched hotel tech pilots", 'Strategy Manager, Mews', ['hotel tech', 'B2B SaaS', 'hospitality systems'], ['property management systems', 'hotel workflow', 'B2B sales'], ['mentor product-minded hospitality students', 'meet people testing hotel software ideas'], ['operator context', 'specific product questions', 'Europe focus'], 'Barcelona, Spain', ['hospitality', 'technology']],
  ['person_20', 'Yara Benali', "Sciences Po '24; research in urban climate adaptation", 'Analyst, C40 Cities', ['climate policy', 'urban planning', 'research careers'], ['city networks', 'adaptation policy', 'public research'], ['help students navigate climate policy', 'meet research-driven peers'], ['policy-specific asks', 'writing samples', 'city context'], 'Paris, France', ['policy', 'climate']],
  ['person_21', 'Thomas Becker', "ETH Zurich '18; ex-McKinsey digital practice", 'Director, Siemens Digital Industries', ['industrial strategy', 'consulting exits', 'digital transformation'], ['manufacturing AI', 'strategy careers', 'Europe industry'], ['help people understand consulting-to-industry paths', 'meet technical strategists'], ['structured questions', 'industry curiosity', 'operator mindset'], 'Munich, Germany', ['consulting', 'technology']],
  ['person_22', 'Aisha Rahman', "Harvard Business School '22; ran student founder office hours", 'Founder, CampusBridge', ['education startups', 'marketplaces', 'student communities'], ['peer networks', 'education access', 'community trust'], ['mentor student founders', 'meet people building useful education tools'], ['student user insight', 'clear experiments', 'mission clarity'], 'Boston, United States', ['education', 'startups']],
  ['person_23', 'Louis Garnier', "EHL '20; revenue management track", 'Revenue Manager, Accor Luxury Division', ['hotel revenue management', 'pricing', 'luxury hotels'], ['room pricing', 'forecasting', 'hotel assets'], ['help students understand hotel commercial roles', 'meet analytical hospitality people'], ['numbers-driven questions', 'hotel context', 'Paris or Geneva'], 'Paris, France', ['hospitality', 'finance']],
  ['person_24', 'Grace Kim', "Stanford '23, Symbolic Systems; built AI tutoring prototype", 'Product Lead, Khan Academy AI', ['AI education', 'product discovery', 'learning design'], ['AI tutors', 'student learning', 'product ethics'], ['help builders test AI education ideas', 'meet thoughtful product people'], ['user research', 'prototype examples', 'student impact'], 'San Francisco, United States', ['ai', 'education']],
  ['person_25', 'Nicolas Weber', "UCL '17, Urban Studies; ex-JLL", 'Asset Manager, Brookfield Properties', ['commercial real estate', 'asset management', 'urban development'], ['office assets', 'city economics', 'real estate careers'], ['help people decode property roles', 'meet city-focused students'], ['real estate focus', 'researched questions', 'UK academic angle'], 'London, United Kingdom', ['real estate', 'finance']],
  ['person_26', 'Sara El-Khoury', "INSEAD MBA '20; scaled food marketplace ops", 'COO, Kitopi Europe', ['food tech', 'operations', 'market expansion'], ['ghost kitchens', 'operations systems', 'growth markets'], ['support practical food initiatives', 'meet operators with field insight'], ['operations questions', 'regional curiosity', 'experiment mindset'], 'Dubai, United Arab Emirates', ['food tech', 'operations']],
  ['person_27', 'Ethan Brooks', "Yale '19; student newspaper editor turned comms strategist", 'Communications Manager, Stripe', ['communications', 'tech careers', 'storytelling'], ['narrative strategy', 'startup comms', 'career pivots'], ['help students communicate projects clearly', 'meet people with sharp writing'], ['writing samples', 'specific audience', 'clear goal'], 'New York, United States', ['technology', 'marketing']],
  ['person_28', 'Beatrice Conti', "Bocconi '18; luxury brand finance", 'Finance Director, Prada Group', ['luxury finance', 'brand strategy', 'italian market'], ['retail economics', 'luxury brands', 'finance careers'], ['help people understand luxury business roles', 'meet finance-curious students'], ['luxury interest', 'prepared questions', 'Milan context'], 'Milan, Italy', ['luxury', 'finance']],
  ['person_29', 'Daniel Meyer', "Oxford '16; ex-hotel acquisitions", 'VP Acquisitions, Ennismore', ['hotel acquisitions', 'hospitality real estate', 'deal underwriting'], ['hotel assets', 'private markets', 'European deals'], ['mentor students studying hospitality real estate', 'meet deal-curious analysts'], ['specific asset questions', 'finance angle', 'Europe context'], 'London, United Kingdom', ['hospitality', 'real estate']],
  ['person_30', 'Mina Park', "MIT '21; robotics lab then product", 'Product Manager, Airbnb Experiences', ['travel marketplaces', 'product strategy', 'user research'], ['experience design', 'marketplace quality', 'travel behavior'], ['help product-curious students', 'meet people studying travel communities'], ['product examples', 'research curiosity', 'concise context'], 'San Francisco, United States', ['travel', 'technology']],
  ['person_31', 'Karim Sayegh', "LSE '22; private equity internship", 'Associate, Blackstone Real Estate', ['real estate private equity', 'financial modeling', 'career recruiting'], ['property finance', 'interview prep', 'asset classes'], ['help students understand REPE recruiting', 'meet focused finance candidates'], ['finance prep', 'specific questions', 'London or Dubai context'], 'London, United Kingdom', ['real estate', 'finance']],
  ['person_32', 'Emma Robertson', "Cambridge '20, Education; founded tutoring nonprofit", 'Program Director, Teach For All', ['education nonprofits', 'program design', 'social impact'], ['teacher networks', 'youth programs', 'impact measurement'], ['mentor education builders', 'meet mission-driven operators'], ['mission clarity', 'program questions', 'student impact'], 'London, United Kingdom', ['education', 'nonprofit']],
  ['person_33', 'Victor Huang', "Wharton '18; consumer investing", 'Investor, L Catterton', ['consumer private equity', 'luxury brands', 'market research'], ['brand diligence', 'consumer behavior', 'luxury investing'], ['help students connect luxury and investing', 'meet analytical brand thinkers'], ['market research', 'brand interest', 'finance focus'], 'New York, United States', ['finance', 'luxury']],
  ['person_34', 'Ana Silva', "Sciences Po '19; UN youth delegate", 'Partnerships Officer, UNESCO', ['international organizations', 'education policy', 'partnerships'], ['global education', 'institutional partnerships', 'policy careers'], ['help students navigate international orgs', 'meet partnership-minded peers'], ['policy-specific questions', 'international context', 'clear motivation'], 'Paris, France', ['policy', 'education']],
  ['person_35', 'Felix Hoffmann', "TU Munich '20; built climate analytics tools", 'Founder, GridLens', ['climate tech', 'energy analytics', 'B2B sales'], ['electric grids', 'climate data', 'enterprise pilots'], ['help technical founders validate climate ideas', 'meet builders with domain curiosity'], ['technical context', 'pilot design', 'clear problem'], 'Berlin, Germany', ['climate', 'startups']],
  ['person_36', 'Lina Chen', "Columbia '21; former admissions interviewer", 'Associate Director, College Advising Corps', ['college advising', 'us universities', 'student mentorship'], ['application strategy', 'first-gen advising', 'student leadership'], ['support students navigating US universities', 'meet thoughtful mentees'], ['student context', 'specific school list', 'clear questions'], 'New York, United States', ['education', 'academia']],
  ['person_37', 'Hannah Müller', "St. Gallen '19; luxury hospitality thesis", 'Consultant, BCG Travel & Tourism', ['travel consulting', 'hospitality strategy', 'case interviews'], ['tourism strategy', 'hotel brands', 'consulting recruiting'], ['help students explore consulting in travel', 'meet structured thinkers'], ['case prep', 'industry focus', 'Europe context'], 'Zurich, Switzerland', ['consulting', 'hospitality']],
  ['person_38', 'Isabella Romano', "Politecnico di Milano '18, Architecture", 'Development Lead, CitizenM Hotels', ['hotel development', 'architecture', 'urban sites'], ['adaptive reuse', 'hotel design', 'city development'], ['help students connect design and hotel assets', 'meet urban thinkers'], ['portfolio context', 'asset questions', 'design angle'], 'Milan, Italy', ['real estate', 'hospitality']],
  ['person_39', 'Samir Patel', "Imperial '22, Computing; student founder", 'ML Engineer, DeepMind', ['machine learning', 'research careers', 'AI products'], ['applied AI', 'research taste', 'student projects'], ['help students understand AI career paths', 'meet serious technical builders'], ['technical questions', 'project examples', 'research curiosity'], 'London, United Kingdom', ['ai', 'technology']],
  ['person_40', 'Olivia Martin', "HEC Paris '21; luxury club president", 'Brand Manager, Cartier', ['luxury marketing', 'brand storytelling', 'paris networks'], ['heritage brands', 'retail experience', 'consumer psychology'], ['help people understand luxury brand roles', 'meet creative strategists'], ['brand interest', 'specific campaign examples', 'Paris context'], 'Paris, France', ['luxury', 'marketing']],
  ['person_41', 'Noah Williams', "Stanford GSB '20; angel investor", 'Founder, Atlas Rooms', ['hospitality startups', 'fundraising', 'marketplaces'], ['room inventory', 'founder-market fit', 'seed fundraising'], ['mentor early hospitality founders', 'meet practical builders'], ['startup context', 'traction signals', 'clear ask'], 'San Francisco, United States', ['hospitality', 'startups']],
  ['person_42', 'Rania Nasser', "Oxford '19; Middle East policy focus", 'Advisor, World Bank', ['development policy', 'middle east markets', 'public finance'], ['development finance', 'regional policy', 'institutional careers'], ['help students explore development careers', 'meet policy researchers'], ['regional curiosity', 'policy-specific asks', 'research context'], 'Washington, United States', ['policy', 'finance']],
  ['person_43', 'Jonas Eriksen', "Copenhagen Business School '18; sustainability track", 'Strategy Lead, Maersk Decarbonization', ['sustainability strategy', 'shipping', 'corporate innovation'], ['green fuels', 'supply chains', 'corporate climate'], ['help people understand corporate climate roles', 'meet systems thinkers'], ['climate focus', 'operator mindset', 'Europe context'], 'Copenhagen, Denmark', ['climate', 'operations']],
  ['person_44', 'Mei Tanaka', "Keio '17; exchange at LSE", 'Director, Aman Resorts', ['luxury resorts', 'hospitality leadership', 'asia markets'], ['resort operations', 'service culture', 'Asia travel'], ['mentor hospitality students', 'meet service-oriented leaders'], ['hospitality focus', 'Asia context', 'specific questions'], 'Tokyo, Japan', ['hospitality', 'luxury']],
  ['person_45', 'Peter Novak', "INSEAD '21; ex-Google partnerships", 'Partnerships Lead, OpenAI for Education', ['AI partnerships', 'education technology', 'go-to-market'], ['school partnerships', 'AI adoption', 'enterprise sales'], ['help builders navigate AI education partnerships', 'meet thoughtful operators'], ['partnership idea', 'education context', 'clear user'], 'Paris, France', ['ai', 'education']],
  ['person_46', 'Fatima Zahra', "ESSEC '20; social entrepreneurship chair", 'Impact Investor, BlueOrchard', ['impact investing', 'emerging markets', 'social enterprise'], ['financial inclusion', 'impact metrics', 'fund strategy'], ['help people understand impact finance', 'meet mission-driven analysts'], ['impact clarity', 'finance questions', 'regional context'], 'Geneva, Switzerland', ['finance', 'nonprofit']],
  ['person_47', 'Jack Thompson', "UCL '20; built student property newsletter", 'Analyst, CBRE Hotels', ['hotel brokerage', 'market research', 'uk property'], ['hotel transactions', 'London market', 'property careers'], ['help students decode hotel brokerage', 'meet research-driven people'], ['UK property angle', 'market questions', 'prepared asks'], 'London, United Kingdom', ['real estate', 'hospitality']],
  ['person_48', 'Chloe Bernard', "Sciences Po '18; public affairs background", 'Public Affairs Lead, BlaBlaCar', ['mobility policy', 'public affairs', 'market expansion'], ['transport regulation', 'platform policy', 'European markets'], ['help people understand policy in startups', 'meet public affairs thinkers'], ['policy and startup context', 'specific country', 'clear ask'], 'Paris, France', ['policy', 'technology']],
  ['person_49', 'Aditya Rao', "IIT Bombay '17; MBA at Wharton", 'VP Product, Duolingo', ['consumer product', 'education apps', 'growth experiments'], ['learning loops', 'experimentation', 'mobile product'], ['mentor product builders', 'meet education product people'], ['product metrics', 'user insight', 'experiment mindset'], 'Pittsburgh, United States', ['education', 'technology']],
  ['person_50', 'Sophie Laurent', "Cambridge '19, Land Economy; family office internships", 'Associate, Ardian Real Estate', ['private real estate', 'european investing', 'asset strategy'], ['European offices', 'fund investing', 'asset management'], ['help students explore real estate investing', 'meet focused analysts'], ['real estate focus', 'UK academic angle', 'finance prep'], 'Paris, France', ['real estate', 'finance']],
].map(([id, name, background, currentRole, expertise, interests, goals, relationshipPreferences, location, industries]) => ({
  id,
  name,
  background,
  currentRole,
  expertise,
  interests,
  goals,
  relationshipPreferences,
  location,
  industries,
  willingToMentor: true,
  contact: `${name.toLowerCase().replace(/[^a-z]+/g, '.').replace(/^\.+|\.+$/g, '')}@example.com`,
  linkedinUrl: `https://www.linkedin.com/in/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}-mock`,
}))

export const mentors = [...coreMentors, ...additionalMentors]
